---
    - name: Upload .tar.gz file containing binaries from local storage
      copy:
         src: "logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
         dest: "/tmp/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
      register: download_logstash
      until: download_logstash is succeeded
      tags: logstash
    - name: Create directrory for logstash
      file:
         state: directory
         path: "{{ logstash_home }}"
      tags: logstash
    - name: Extract Logstash archive in /opt/logstash
      become: true
      unarchive:
         copy: false
         src: "/tmp/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
         dest: "{{ logstash_home }}"
         extra_opts: [--strip-components=1]
         creates: "{{ logstash_home }}/bin"
      tags: logstash
    - name: Set environment for Logstash
      become: true
      template:
         src: templates/logstash.sh.j2
         dest: /etc/profile.d/logstash.sh
         mode: 0777
      tags: logstash
    - name: Put on logstash file
      become: true
      template:
        src: templates/logstash.conf.j2
        dest: "{{ elastic_home }}/config/logstash.conf"
        mode: 0755
    - name: Ensure user logstash exists
      user:
        user: logstash
        group: root
        uid: 2003
        password: "{{ 'pass' | password_hash('sha512') }}"
        state: present
    - name: Set own to logstash directory
      file:
         path: /opt/logstash/
         recurse: yes
         state: directory
         owner: logstash
         mode: 0777
      tags: Set_own
    - name: Start Logstash
      become_user: logstash
      become_method: su
      shell: "{{ logstash_home }}/bin/logstash"

